/******************************************************
 * This is the main file for the mips1 ArchC model    *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 
// Rodolfo editou aqui
//
const char *project_name="mips1";
const char *project_file="mips1.ac";
const char *archc_version="2.0beta1";
const char *archc_options="-abi -dy ";

#include  <systemc.h>
#include  "mips1.H"
#include  "ac_tlm_mem.h"
#include  "ac_tlm_bus.h"

int sc_main(int ac, char *av[])
{

  //!  ISA simulator
  mips1 mips1_proc0("mips0");
  ac_tlm_mem mem("mem");
  ac_tlm_bus bus("bus");

#ifdef AC_DEBUG
  ac_trace("mips1_proc0.trace");
#endif 

  mips1_proc0.DM_port(bus.cpu0_target_export);

  bus.mem_port(mem.target_export);
  
  mips1_proc0.init(ac, av);
  cerr << endl;

  sc_start();

  mips1_proc0.PrintStat();
  cerr << endl;

#ifdef AC_STATS
  mips1_proc0.ac_sim_stats.time = sc_simulation_time();
  mips1_proc0.ac_sim_stats.print();
#endif 

#ifdef AC_DEBUG
  ac_close_trace();
#endif 

  return mips1_proc0.ac_exit_status;
}
